In [32]:
import pandas as pd

In [33]:
df = pd.read_csv("../data/clean_traffy.csv")

/tmp/ipykernel_3413/2370604870.py:1: DtypeWarning: Columns (3,4,8,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/clean_traffy.csv")

In [34]:
df

,address,comment,coords,description,description_en,district,organization,province,source,subdistrict,timestamp,title,title_en,type
0,189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,"100.66709,13.67891",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",กรุงเทพ,NaN,หนองบอน,2021-09-19 14:56:08.924992+00:00,NaN,NaN,"['น้ำท่วม', 'ร้องเรียน']"
1,191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,"100.52649,13.72060",NaN,NaN,สาทร,เขตสาทร,กรุงเทพ,NaN,ยานนาวา,2021-09-26 05:03:52.594898+00:00,NaN,NaN,['สะพาน']
2,702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,"100.59165,13.82280",NaN,NaN,ลาดพร้าว,"เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",กรุงเทพ,NaN,ลาดพร้าว,2021-12-09 12:29:08.408763+00:00,NaN,NaN,"['น้ำท่วม', 'ถนน']"
3,110 ซอย มีสุข แขวง หนองบอน เขต ประเวศ กรุงเทพม...,คนเอาขยะมาทิ้งจนกลายเป็นกองขยะค่ะ,"100.64690,13.67083",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ,ฝ่ายรักษาความสะ...",กรุงเทพ,NaN,หนองบอน,2021-12-18 14:50:52.437512+00:00,NaN,NaN,['ความสะอาด']
4,70 ซอย เฉลิมพระเกียรติ ร. 9 แขวง หนองบอน เขต ป...,ขอแจ้งเรื่องท่อระบายน้ำบนถนนในซอยเสียหาย เป็นร...,"100.65440,13.68158",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",กรุงเทพ,NaN,หนองบอน,2021-12-22 10:15:33.294829+00:00,NaN,NaN,['ท่อระบายน้ำ']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692912,NaN,NaN,"100.42299,13.57341",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนบางขุนเทียน...,Motorcycle accident on Bang Khun Thian Chai Th...,บางขุนเทียน,NaN,กรุงเทพ,RVP,ท่าข้าม,NaN,อุบัติเหตุ บางขุนเทียน-ชายทะเล,Accident at Bang Khun Thian-Chai Thale Rd.,['อุบัติเหตุ']
692913,NaN,NaN,"100.42130,13.57129",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนบางขุนเทียน...,Motorcycle accident on Bang Khun Thian Chai Th...,บางขุนเทียน,NaN,กรุงเทพ,RVP,ท่าข้าม,NaN,อุบัติเหตุ บางขุนเทียน-ชายทะเล,Accident at Bang Khun Thian-Chai Thale Rd.,['อุบัติเหตุ']
692914,NaN,NaN,"100.49529,13.68289",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ สุขสวัสดิ์ 19 ...,"Motorcycle accident on Suk Sawat 19, Bang Pa K...",ราษฎร์บูรณะ,NaN,กรุงเทพ,RVP,บางปะกอก,NaN,อุบัติเหตุ บางปะกอก,Accident at Suk Sawat 19,['อุบัติเหตุ']
692915,NaN,NaN,"100.64514,13.81752",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนประดิษฐ์มนู...,Motorcycle accident on Pradit Manutham Rd. at ...,บึงกุ่ม,NaN,กรุงเทพ,RVP,นวลจันทร์,NaN,อุบัติเหตุ,Accident at Nuanchan Rd.,['อุบัติเหตุ']
692916,NaN,NaN,"100.68063,13.67427",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ แขวงดอกไม้ เขต...,"Motorcycle accident on Dok Mai, Prawet, Bangko...",ประเวศ,NaN,กรุงเทพ,RVP,ดอกไม้,NaN,อุบัติเหตุ ดอกไม้,Accident at Dokmai,['อุบัติเหตุ']

In [35]:
df[['lon','lat']] = df['coords'].str.split(',', expand=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692917 entries, 0 to 692916
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   address         664427 non-null  object
 1   comment         664427 non-null  object
 2   coords          692917 non-null  object
 3   description     28490 non-null   object
 4   description_en  28490 non-null   object
 5   district        692917 non-null  object
 6   organization    664328 non-null  object
 7   province        692917 non-null  object
 8   source          28490 non-null   object
 9   subdistrict     692917 non-null  object
 10  timestamp       664427 non-null  object
 11  title           28490 non-null   object
 12  title_en        28490 non-null   object
 13  type            692917 non-null  object
 14  lon             692917 non-null  object
 15  lat             692917 non-null  object
dtypes: object(16)
memory usage: 84.6+ MB

In [37]:
district_list = df["district"].unique().tolist()

district_list

['ประเวศ',
 'สาทร',
 'ลาดพร้าว',
 'ดุสิต',
 'ลาดกระบัง',
 'วัฒนา',
 'คลองสาน',
 'ปทุมวัน',
 'ตลิ่งชัน',
 'ดอนเมือง',
 'ห้วยขวาง',
 'สะพานสูง',
 'สวนหลวง',
 'หลักสี่',
 'ธนบุรี',
 'บางนา',
 'ทุ่งครุ',
 'บางแค',
 'คลองสามวา',
 'จตุจักร',
 'บางเขน',
 'สายไหม',
 'บางซื่อ',
 'ภาษีเจริญ',
 'ดินแดง',
 'บางกอกน้อย',
 'วังทองหลาง',
 'ราษฎร์บูรณะ',
 'ราชเทวี',
 'บางขุนเทียน',
 'พระโขนง',
 'พระนคร',
 'บึงกุ่ม',
 'พญาไท',
 'จอมทอง',
 'มีนบุรี',
 'บางกอกใหญ่',
 'บางกะปิ',
 'บางคอแหลม',
 'หนองจอก',
 'ยานนาวา',
 'บางพลัด',
 'คลองเตย',
 'บางบอน',
 'คันนายาว',
 'หนองแขม',
 'สัมพันธวงศ์',
 'บางรัก',
 'ป้อมปราบศัตรูพ่าย',
 'ทวีวัฒนา',
 'บางกรวย',
 'บางพลี',
 'พระประแดง',
 'ลำลูกกา',
 'สามพราน']

In [38]:
from sklearn.cluster import KMeans
for district in district_list:
    mask = df["district"] == district
    X = df.loc[mask, ["lat","lon"]]
    kmeans = KMeans(n_clusters=min(3, X.shape[0]), random_state=42)
    df.loc[mask, "cluster_label"] = kmeans.fit_predict(X)

In [39]:
import ast
df['type'] = df['type'].apply(ast.literal_eval)

In [40]:
df = df.explode("type", ignore_index=True)

In [41]:
df

,address,comment,coords,description,description_en,district,organization,province,source,subdistrict,timestamp,title,title_en,type,lon,lat,cluster_label
0,189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,"100.66709,13.67891",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",กรุงเทพ,NaN,หนองบอน,2021-09-19 14:56:08.924992+00:00,NaN,NaN,น้ำท่วม,100.66709,13.67891,2.0
1,189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,"100.66709,13.67891",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",กรุงเทพ,NaN,หนองบอน,2021-09-19 14:56:08.924992+00:00,NaN,NaN,ร้องเรียน,100.66709,13.67891,2.0
2,191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,"100.52649,13.72060",NaN,NaN,สาทร,เขตสาทร,กรุงเทพ,NaN,ยานนาวา,2021-09-26 05:03:52.594898+00:00,NaN,NaN,สะพาน,100.52649,13.72060,2.0
3,702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,"100.59165,13.82280",NaN,NaN,ลาดพร้าว,"เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",กรุงเทพ,NaN,ลาดพร้าว,2021-12-09 12:29:08.408763+00:00,NaN,NaN,น้ำท่วม,100.59165,13.82280,0.0
4,702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,"100.59165,13.82280",NaN,NaN,ลาดพร้าว,"เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",กรุงเทพ,NaN,ลาดพร้าว,2021-12-09 12:29:08.408763+00:00,NaN,NaN,ถนน,100.59165,13.82280,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1091839,NaN,NaN,"100.42299,13.57341",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนบางขุนเทียน...,Motorcycle accident on Bang Khun Thian Chai Th...,บางขุนเทียน,NaN,กรุงเทพ,RVP,ท่าข้าม,NaN,อุบัติเหตุ บางขุนเทียน-ชายทะเล,Accident at Bang Khun Thian-Chai Thale Rd.,อุบัติเหตุ,100.42299,13.57341,2.0
1091840,NaN,NaN,"100.42130,13.57129",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนบางขุนเทียน...,Motorcycle accident on Bang Khun Thian Chai Th...,บางขุนเทียน,NaN,กรุงเทพ,RVP,ท่าข้าม,NaN,อุบัติเหตุ บางขุนเทียน-ชายทะเล,Accident at Bang Khun Thian-Chai Thale Rd.,อุบัติเหตุ,100.42130,13.57129,2.0
1091841,NaN,NaN,"100.49529,13.68289",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ สุขสวัสดิ์ 19 ...,"Motorcycle accident on Suk Sawat 19, Bang Pa K...",ราษฎร์บูรณะ,NaN,กรุงเทพ,RVP,บางปะกอก,NaN,อุบัติเหตุ บางปะกอก,Accident at Suk Sawat 19,อุบัติเหตุ,100.49529,13.68289,0.0
1091842,NaN,NaN,"100.64514,13.81752",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนประดิษฐ์มนู...,Motorcycle accident on Pradit Manutham Rd. at ...,บึงกุ่ม,NaN,กรุงเทพ,RVP,นวลจันทร์,NaN,อุบัติเหตุ,Accident at Nuanchan Rd.,อุบัติเหตุ,100.64514,13.81752,2.0
1091843,NaN,NaN,"100.68063,13.67427",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ แขวงดอกไม้ เขต...,"Motorcycle accident on Dok Mai, Prawet, Bangko...",ประเวศ,NaN,กรุงเทพ,RVP,ดอกไม้,NaN,อุบัติเหตุ ดอกไม้,Accident at Dokmai,อุบัติเหตุ,100.68063,13.67427,2.0

In [42]:
import pandasql

cluster_df = pandasql.sqldf("""
            with query_cluster as (
            select cluster_label,district, type, count(*) as count_type, row_number() over (partition by cluster_label,district order by count(*) desc) as rn
            from df group by cluster_label, district, type order by cluster_label,district, count_type desc
            )
            select q.cluster_label,q.district ,q.type as top_type, q.count_type as top_type_count from query_cluster q where q.rn <= 3;
            """)
cluster_df

     cluster_label   district     top_type  top_type_count
0              0.0    คลองสาน          ถนน            1009
1              0.0    คลองสาน      ทางเท้า             470
2              0.0    คลองสาน  ความปลอดภัย             329
3              0.0  คลองสามวา          ถนน            2237
4              0.0  คลองสามวา    ความสะอาด             563
..             ...        ...          ...             ...
465            2.0    หลักสี่         ป้าย             521
466            2.0    หลักสี่     แสงสว่าง             337
467            2.0   ห้วยขวาง          ถนน            1720
468            2.0   ห้วยขวาง     แสงสว่าง             603
469            2.0   ห้วยขวาง  ความปลอดภัย             530

[470 rows x 4 columns]

In [43]:
cluster_df = cluster_df.groupby(['cluster_label', 'district'])[['top_type', 'top_type_count']].agg(tuple).reset_index()

In [44]:
df = df.merge(cluster_df, on=["cluster_label", "district"], how="left")

In [45]:
df

,address,comment,coords,description,description_en,district,organization,province,source,subdistrict,timestamp,title,title_en,type,lon,lat,cluster_label,top_type,top_type_count
0,189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,"100.66709,13.67891",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",กรุงเทพ,NaN,หนองบอน,2021-09-19 14:56:08.924992+00:00,NaN,NaN,น้ำท่วม,100.66709,13.67891,2.0,"(ถนน, น้ำท่วม, ความสะอาด)","(2261, 947, 870)"
1,189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,"100.66709,13.67891",NaN,NaN,ประเวศ,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",กรุงเทพ,NaN,หนองบอน,2021-09-19 14:56:08.924992+00:00,NaN,NaN,ร้องเรียน,100.66709,13.67891,2.0,"(ถนน, น้ำท่วม, ความสะอาด)","(2261, 947, 870)"
2,191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,"100.52649,13.72060",NaN,NaN,สาทร,เขตสาทร,กรุงเทพ,NaN,ยานนาวา,2021-09-26 05:03:52.594898+00:00,NaN,NaN,สะพาน,100.52649,13.72060,2.0,"(ถนน, ทางเท้า, กีดขวาง)","(1446, 969, 698)"
3,702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,"100.59165,13.82280",NaN,NaN,ลาดพร้าว,"เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",กรุงเทพ,NaN,ลาดพร้าว,2021-12-09 12:29:08.408763+00:00,NaN,NaN,น้ำท่วม,100.59165,13.82280,0.0,"(ถนน, ความสะอาด, ความปลอดภัย)","(1663, 578, 531)"
4,702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,"100.59165,13.82280",NaN,NaN,ลาดพร้าว,"เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",กรุงเทพ,NaN,ลาดพร้าว,2021-12-09 12:29:08.408763+00:00,NaN,NaN,ถนน,100.59165,13.82280,0.0,"(ถนน, ความสะอาด, ความปลอดภัย)","(1663, 578, 531)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1091839,NaN,NaN,"100.42299,13.57341",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนบางขุนเทียน...,Motorcycle accident on Bang Khun Thian Chai Th...,บางขุนเทียน,NaN,กรุงเทพ,RVP,ท่าข้าม,NaN,อุบัติเหตุ บางขุนเทียน-ชายทะเล,Accident at Bang Khun Thian-Chai Thale Rd.,อุบัติเหตุ,100.42299,13.57341,2.0,"(ถนน, อุบัติเหตุ, น้ำท่วม)","(2647, 643, 614)"
1091840,NaN,NaN,"100.42130,13.57129",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนบางขุนเทียน...,Motorcycle accident on Bang Khun Thian Chai Th...,บางขุนเทียน,NaN,กรุงเทพ,RVP,ท่าข้าม,NaN,อุบัติเหตุ บางขุนเทียน-ชายทะเล,Accident at Bang Khun Thian-Chai Thale Rd.,อุบัติเหตุ,100.42130,13.57129,2.0,"(ถนน, อุบัติเหตุ, น้ำท่วม)","(2647, 643, 614)"
1091841,NaN,NaN,"100.49529,13.68289",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ สุขสวัสดิ์ 19 ...,"Motorcycle accident on Suk Sawat 19, Bang Pa K...",ราษฎร์บูรณะ,NaN,กรุงเทพ,RVP,บางปะกอก,NaN,อุบัติเหตุ บางปะกอก,Accident at Suk Sawat 19,อุบัติเหตุ,100.49529,13.68289,0.0,"(ถนน, ทางเท้า, ความปลอดภัย)","(929, 472, 324)"
1091842,NaN,NaN,"100.64514,13.81752",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ ถนนประดิษฐ์มนู...,Motorcycle accident on Pradit Manutham Rd. at ...,บึงกุ่ม,NaN,กรุงเทพ,RVP,นวลจันทร์,NaN,อุบัติเหตุ,Accident at Nuanchan Rd.,อุบัติเหตุ,100.64514,13.81752,2.0,"(ถนน, ทางเท้า, ความสะอาด)","(2166, 914, 896)"
1091843,NaN,NaN,"100.68063,13.67427",เกิดอุบัติเหตุรถจักรยานยนต์ ที่ แขวงดอกไม้ เขต...,"Motorcycle accident on Dok Mai, Prawet, Bangko...",ประเวศ,NaN,กรุงเทพ,RVP,ดอกไม้,NaN,อุบัติเหตุ ดอกไม้,Accident at Dokmai,อุบัติเหตุ,100.68063,13.67427,2.0,"(ถนน, น้ำท่วม, ความสะอาด)","(2261, 947, 870)"

In [46]:
clustered_df = df[["coords", "district","cluster_label", "top_type", "top_type_count"]].drop_duplicates(inplace=False)

In [47]:
clustered_df.to_csv("../data/clustered_traffy.csv", index=False)